### ISSUE TITLE
Turbolinks

### ISSUE THREAD

**Issue by drewpotter** [peterkeen/payola#102]
Hello,

I was just wondering if support for turbolinks will be added in the future?

Thanks,

Drew

**Comment by TrevorHinesley** [comment]
@peterkeen total side note, but I'm actually curious what your thoughts are on Turbolinks in general. I've begun ripping it out of all new Rails apps I create. Too much of a headache when trying to use it with lots of AJAX or otherwise dynamic content.

**Comment by peterkeen** [comment]
@drewpotter It's unlikely that I'll be adding it myself. Like @TrevorHinesley I find myself ripping it out, since in my experience it just adds a bunch of new failure cases with very little practical benefit.

**Comment by peterkeen** [comment]
Closing for now.

**Comment by archonic** [comment]
With Rails5 around the corner and Turbolinks 3 being pretty awesome, I'd appreciate support. If I have to chose between the two, Payola will lose.

@TrevorHinesley (Turbolinks events)[https://github.com/rails/turbolinks#events] end up providing more refined triggers than ajax complete, ajax success and document ready. Once the change is made, I find it very worthwhile. Especially partial replacement since that's most of the reason my JS was getting out of control.

**Comment by TrevorHinesley** [comment]
@archonic gotta be honest, this is still a bad idea, in my opinion. I'm very familiar with turbolinks, but it is its own beast, and though it's Rails' default, myself and many others (like Pete agreed) rip it out due to issues that arise by how it binds. If @peterkeen or someone else wants to start working on integration, that's totally fine (and you're welcome to as well!), but unfortunately, I don't have any desire to tackle this.
