### ISSUE TITLE
Stripe::AuthenticationError in Payola::SubscriptionsController#destroy

### ISSUE THREAD

**Issue by jagthedrummer** [peterkeen/payola#73]
When I try to cancel an account using the built in helper button I'm getting `Stripe::AuthenticationError in Payola::SubscriptionsController#destroy`.

The source of the error is the `Payola::CancelSubscription` service. I've tried adding the `secret_key` into the call to `delete`, with no luck, like so:

```
customer.subscriptions.retrieve(subscription.stripe_id,secret_key).delete(secret_key)
```

I have found that adding this:

```
Stripe.api_key = secret_key
```

before the call to delete will fix the problem.  Not sure if we're specifically avoiding doing that.

The Stripe documentation makes it sound like this may be a bug in the Stripe Ruby lib.

https://stripe.com/docs/api/ruby#authentication

"...or you can always pass a key directly to an object's constructor. Authentication is transparently handled for you in subsequent method calls."

**Comment by jagthedrummer** [comment]
Happy to whip up a PR if setting `Stipre.api_key` is an OK approach.

**Comment by peterkeen** [comment]
I don't think that that's the correct approach, since that sets the key
globally from then on. It looks like in v1.17 the way that you pass an API
key to create and delete changed, which is *hella* inconvenient,
backwards-compatibility-wise.

https://github.com/stripe/stripe-ruby/blob/v1.17.0/lib/stripe/api_operations/delete.rb#L5

I'll make an issue on the stripe-ruby repo and see if we can get that
addressed.

**Comment by peterkeen** [comment]
Oh, spoke too soon. The parse_opts method does the right thing. We just
need to pass the arguments correctly. I'll patch it up.

**Comment by jagthedrummer** [comment]
Yeah, I was just looking at that too and got a PR ready : https://github.com/peterkeen/payola/pull/74
