### ISSUE TITLE
Allow in-line processing

### ISSUE THREAD

**Issue by TrevorHinesley** [peterkeen/payola#78]
This is something I've talked to a few other developers about in passing, and I think for usability's sake, it might make sense to at least allow for in-line processing of purchases and subscriptions. Personally, I would prefer inline. Especially, if not solely, for subscriptions. 

There are very few sites that I can think of that would ever be riddled with bottlenecked web servers due to hogging by subscription processes. This is something that most users will do one time. For most subscription based services, they rarely change their plans, or they do so very sparingly. I would rather have immediate feedback than have to deal with any async issues that could arise. Thoughts on allowing this?

**Comment by peterkeen** [comment]
The point of async isn't dealing with bottlenecked web servers, it's dealing with Stripe being slow. I had a consulting client bit by [Stripe API slowness][1] (not downtime, just slow) five days ago because they're not doing async payments. They found out when the customer wrote an angry email when they got charged but didn't get their subscription because their web session timed out.

So no, Payola will not build in support for customer-facing inline payments. You can fake it by changing the background worker to a lambda that just does the work immediately (as described [in the wiki][2]).

[1]: https://twitter.com/stripestatus/status/553326599358386176
[2]: https://github.com/peterkeen/payola/wiki/Configuration-options#background-jobs

**Comment by TrevorHinesley** [comment]
Makes perfect sense. Sorry for the dumb question haha!

**Comment by msaspence** [comment]
Can I reopen this I think I've found a specific use case that makes this relevant:

* User subscribes 
* Page is returned to user
* Payola::ProcessSubscription is queue but the background worker is a bit behind so there is a delay on it
* Stripe calls a custom web hook subscription that I've set up, in that I want to look up a user using their stripe customer id, but since Payola::ProcessSubscription hasn't run yet I can't
* Payola::ProcessSubscription is run and stripe_customer_id is persisted to the db, but it is too late for my web hook
